name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.5.0
      - name: Setup TFCDK Environment
        run: npm install --global cdktf-cli@latest

  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Deploy
        run: |
          cd tf-safetorun
          go build
          mv tf-safetorun terraform-provider-safetorun
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: tf-safetorun/terraform-provider-safetorun
          fail_on_unmatched_files: true